In [1]:
import numpy as np

In [2]:
#Addition of Array
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
c=a1+a2
print(c)

[ 7  9 11 13 15]


In [3]:
#Addition of Lists
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
c=l1+l2
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
#2d Array
arr2d =np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [6]:
type(l1)

list

In [7]:
al1=np.array(l1)
print(al1)

[1 2 3 4 5]


In [8]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [9]:
f1=np.ones(4)
print(f1)

[1. 1. 1. 1.]


In [10]:
f1=np.ones(4,dtype=int)
print(f1)

[1 1 1 1]


In [11]:
f2=np.ones((5,3),dtype=int)
print(f2)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
z1=np.zeros(6)
print(z1)

[0. 0. 0. 0. 0. 0.]


In [13]:
z1=np.zeros(3,dtype=int)
print(z1)

[0 0 0]


In [14]:
r1=np.random.random(10)
print(r1)

[0.16951056 0.16356202 0.33430567 0.3826065  0.34506706 0.58424616
 0.09899202 0.45567283 0.6960624  0.88566488]


In [15]:
r2=np.linspace(3,10,2,dtype=int)
print(r2)

[ 3 10]


In [16]:
r2=np.linspace(5,10,4)
print(r2)

[ 5.          6.66666667  8.33333333 10.        ]


In [17]:
z2=np.arange(5,100,5)
print(z2)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [18]:
z2.shape

(19,)

In [19]:
f2.shape

(5, 3)

In [20]:
f2.ndim

2

In [21]:
f2.itemsize

8

In [22]:
f2.dtype

dtype('int64')

In [23]:
e1=np.arange(2,32,2)
print(e1)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [24]:
e1[[0,1,2]]

array([2, 4, 6])

In [25]:
e1[4]

10

In [26]:
e1[5:10]

array([12, 14, 16, 18, 20])

In [27]:
rsq=e1**2
for sq in rsq:
    print(sq)

4
16
36
64
100
144
196
256
324
400
484
576
676
784
900


In [28]:
for i in e1:
    if(i%4==0):
        print(i)

4
8
12
16
20
24
28


In [29]:
r=f2.reshape(3,5)
print(r)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [30]:
a1=np.arange(1,9)
a2=np.arange(9,17)
print(a1)
print(a2)

[1 2 3 4 5 6 7 8]
[ 9 10 11 12 13 14 15 16]


In [33]:
h1=np.hstack((a1,a2))
v1=np.vstack((a1,a2))
print(h1)
print(v1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [32]:
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    vstack : Stac