# Numpy Tutorial

Numpy is general-purpose array-processing package. it provides a high-performance multidimentional array object, and tools for working with thesde arrays. it is a fundamental package for scintific computing with python.

# What is an Array?

An array is data structure that stores values of same data type. In python, this is the main difference between arrays and lists. while python containing values and corresponding to different data types, arrays in python can only contain values corresponding to same data type.

In [1]:
import numpy as np

In [2]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(5,)

In [5]:
## MultiDimentional Array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [3,4,5,6,7]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [6]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [7]:
arr.shape

(3, 5)

In [8]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [9]:
arr.shape

(3, 5)

# Indexing

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[5]

6

In [13]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [3,4,5,6,7]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [15]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [16]:
arr[1:,3:]

array([[5, 6],
       [6, 7]])

In [17]:
arr[1:,2:4]

array([[4, 5],
       [5, 6]])

In [18]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [19]:
# Inbuilt functions.

arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr = np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [22]:
## copy function and broadcasting
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[3:]=100
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr1 = arr

In [25]:
arr1[3:] = 500
print(arr1)

[  0   1   2 500 500 500 500 500 500 500]


In [26]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [27]:
arr1 = arr.copy()

In [28]:
print(arr)
arr1[3:] = 1000
print(arr1)

[  0   1   2 500 500 500 500 500 500 500]
[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [29]:
## some conditions useful in Expoloratory data analysis.
val=2
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [30]:
arr*3

array([   0,    3,    6, 1500, 1500, 1500, 1500, 1500, 1500, 1500])

In [31]:
## Create arrays and reshape.
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
# ones array
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
# random distribution

np.random.rand(3,3)

array([[0.57671388, 0.79002468, 0.7977586 ],
       [0.63443624, 0.08630906, 0.8574239 ],
       [0.04743057, 0.49437012, 0.68588782]])

In [35]:
arr_ex = np.random.randn(4,4)
arr_ex

array([[ 0.42485087, -0.38736601, -1.01220716,  0.91783306],
       [-0.85939175,  0.25217503,  1.02468301,  1.27787167],
       [-0.04274821,  1.00982318,  1.17684535,  1.18072603],
       [-0.17485066, -0.29242118,  0.36507054,  0.1517659 ]])

In [39]:
np.random

TypeError: 'numpy.ndarray' object is not callable